FROM node:20.6.0

WORKDIR /webapp

COPY package.json package-lock.json /webapp/

RUN npm install

COPY . . 

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build",  "-l", "3000"]
